#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

PLUGIN_DIR="$(CDPATH= cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PIDS=("1890" "1892")   # wireless dongle, wired

# have_hid — true if the running python3 can import the hid module.
have_hid() { python3 -c "import hid" >/dev/null 2>&1; }

# udev_covers PID — true if some rule under /etc/udev/rules.d already grants
# hidraw MODE=0666 to this vendor:PID. Checked by content, not filename —
# rivalcfg's own --update-udev, or a previous run of this script, may have
# already written a covering rule under a different name.
udev_covers() {
  local pid="$1" f
  for f in /etc/udev/rules.d/*.rules; do
    [[ -f "$f" ]] || continue
    if grep -q 'idVendor}=="1038"' "$f" && grep -q "idProduct}==\"$pid\"" "$f" && grep -q 'hidraw' "$f"; then
      return 0
    fi
  done
  return 1
}

TOTAL_STAGES=3
TOTAL_MINUTES=3

## Custom intro instead of banner(): that helper's built-in subtext talks
## about driving a browser and copying back credential values, neither of
## which applies to a local package/udev-rule check — so this writes its own
## short intro with the same _clear + pause framing instead.
_clear
printf '\n%s%s  Aerox 3 Battery — plugin setup%s\n' "$BOLD" "$BLUE" "$RESET"
printf '%s  %s stages · about %s minutes%s\n\n' "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
say "Installs the two things the plugin can't ship for you: the hidapi"
say "Python module, and a udev rule so it can read the mouse without root."
say "Safe to re-run any time — anything already done is skipped."
pause "Ready to start?"

# ── Stage 1: hidapi Python module ──────────────────────────────────────────
stage "hidapi Python module" 1

if have_hid; then
  note "already installed — python3 can import hid. Skipping."
else
  say "python3 can't import the hid module yet."
  installed=0

  if command -v pacman >/dev/null 2>&1; then
    say "Detected pacman — trying the native package (python-hidapi)."
    if confirm "Run: sudo pacman -S --needed python-hidapi ?"; then
      if sudo pacman -S --needed --noconfirm python-hidapi; then
        installed=1
      else
        warn "pacman install failed or was cancelled."
      fi
    fi
  elif command -v apt-get >/dev/null 2>&1; then
    say "Detected apt — trying the native package (python3-hid)."
    if confirm "Run: sudo apt-get install -y python3-hid ?"; then
      if sudo apt-get install -y python3-hid; then
        installed=1
      else
        warn "apt package not found or install failed — will try pip instead."
      fi
    fi
  elif command -v dnf >/dev/null 2>&1; then
    say "Detected dnf — trying the native package (python3-hidapi)."
    if confirm "Run: sudo dnf install -y python3-hidapi ?"; then
      if sudo dnf install -y python3-hidapi; then
        installed=1
      else
        warn "dnf package not found or install failed — will try pip instead."
      fi
    fi
  fi

  if [[ "$installed" -eq 0 ]] && have_hid; then
    # A native package install above can silently succeed against a
    # different python3 than the one on PATH (e.g. distro python vs pyenv) —
    # re-check rather than trusting the exit code alone.
    installed=1
  fi

  if [[ "$installed" -eq 0 ]]; then
    say "Falling back to pip: pip install --user hidapi"
    if confirm "Run: pip install --user hidapi ?"; then
      if pip install --user hidapi 2>/tmp/aerox3-pip-error.log; then
        installed=1
      elif grep -qi "externally-managed-environment" /tmp/aerox3-pip-error.log 2>/dev/null; then
        warn "pip refused: this Python is externally managed (PEP 668)."
        note "Overriding this can affect distro-managed packages system-wide."
        if confirm "Override anyway with --break-system-packages?"; then
          pip install --user --break-system-packages hidapi && installed=1
        fi
      fi
      rm -f /tmp/aerox3-pip-error.log
    fi
  fi

  if [[ "$installed" -eq 1 ]] && have_hid; then
    printf '  %s✓%s hidapi installed and importable.\n' "$GREEN" "$RESET"
  else
    warn "hidapi still isn't importable by python3."
    SKIPPED+=("Install hidapi so 'python3 -c \"import hid\"' succeeds — see the plugin README")
  fi
fi

# ── Stage 2: udev rule ──────────────────────────────────────────────────────
stage "udev rule for hidraw access" 1

missing_pids=()
for pid in "${PIDS[@]}"; do
  if udev_covers "$pid"; then
    note "PID 1038:$pid already covered by an existing udev rule."
  else
    missing_pids+=("$pid")
  fi
done

if [[ "${#missing_pids[@]}" -eq 0 ]]; then
  note "Both PIDs already covered. Skipping."
else
  say "Missing a udev rule for: ${missing_pids[*]/#/1038:}"
  say "Without it, every HID read fails with a permissions error even with"
  say "hidapi installed and the mouse connected."
  rule_file="/etc/udev/rules.d/99-steelseries-aerox3-gen2.rules"
  {
    echo "# Installed by dms-aerox3-battery-widget/setup.sh"
    for pid in "${missing_pids[@]}"; do
      echo "SUBSYSTEM==\"hidraw\", ATTRS{idVendor}==\"1038\", ATTRS{idProduct}==\"$pid\", MODE=\"0666\""
      echo "SUBSYSTEM==\"usb\",    ATTRS{idVendor}==\"1038\", ATTRS{idProduct}==\"$pid\", MODE=\"0666\""
    done
  } > /tmp/aerox3-udev-rule.tmp
  say "Will write $rule_file:"
  sed 's/^/    /' /tmp/aerox3-udev-rule.tmp
  if confirm "Write this rule (needs sudo) and reload udev?"; then
    if sudo install -m 0644 /tmp/aerox3-udev-rule.tmp "$rule_file" \
       && sudo udevadm control --reload-rules \
       && sudo udevadm trigger; then
      printf '  %s✓%s Rule written and udev reloaded.\n' "$GREEN" "$RESET"
      note "Unplug and replug the mouse (or power-cycle the dongle) if it's"
      note "already connected — udev only re-labels devices as they attach."
    else
      warn "Writing the rule or reloading udev failed."
      SKIPPED+=("Write $rule_file manually — see the plugin README for the exact contents")
    fi
  else
    SKIPPED+=("Write $rule_file — see the plugin README for the exact contents")
  fi
  rm -f /tmp/aerox3-udev-rule.tmp
fi

# ── Stage 3: live check ─────────────────────────────────────────────────────
stage "Live check" 1

say "Running the plugin's own battery-level script..."
if output=$("$PLUGIN_DIR/scripts/battery-level.sh" 2>&1); then
  case "$output" in
    "Charging ["* | "Discharging ["*)
      printf '  %s✓ Working:%s %s\n' "$GREEN" "$RESET" "$output"
      ;;
    *)
      warn "Script ran but returned something unexpected:"
      note "  $output"
      SKIPPED+=("Investigate unexpected output: $output")
      ;;
  esac
else
  case "$output" in
    "E: hidapi module not installed")
      warn "Still can't import hid — stage 1 above didn't fully complete."
      SKIPPED+=("Re-run this script after installing hidapi, or install it manually")
      ;;
    *"No supported device found"*)
      warn "hidapi and udev look fine, but the mouse wasn't found."
      note "Make sure it's powered on and connected (dongle or USB cable),"
      note "then re-run this script or just wait for the widget's next poll."
      ;;
    *)
      warn "Script failed: $output"
      SKIPPED+=("Investigate script failure: $output")
      ;;
  esac
fi

finish
